version: '3'
name: zero
services:
  db:
    image: postgres:16
    container_name: zero_db
    environment:
      POSTGRES_USER: zero
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zero
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: zero_mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port

volumes:
  db_data: